# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 23:45
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogtagindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('sub_heading', wagtail.wagtailcore.blocks.CharBlock(classname='sub title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('carousel', wagtail.wagtailcore.blocks.StructBlock((('alt', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock())))))),
        ),
    ]
