# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 17:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailcore', '0039_collectionviewrestriction'),
        ('blog', '0012_auto_20170703_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Creation Date')),
                ('end_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Creation Date')),
                ('location', models.CharField(max_length=250)),
                ('intro', models.CharField(max_length=250)),
                ('content', wagtail.wagtailcore.fields.StreamField((('sub_heading', wagtail.wagtailcore.blocks.CharBlock(classname='sub title')), ('body', wagtail.wagtailcore.blocks.RichTextBlock()), ('gallery', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.CharBlock()))), template='blog/blocks/carousel.html'))), blank=True, null=True)),
                ('tags', modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPageTag', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='blogpagegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogpagegalleryimage',
            name='page',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('sub_heading', wagtail.wagtailcore.blocks.CharBlock(classname='sub title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('gallery', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.CharBlock()))), template='blog/blocks/carousel.html'))), blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BlogPageGalleryImage',
        ),
    ]
