# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0039_collectionviewrestriction'),
        ('blog', '0013_auto_20170704_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='tags',
        ),
        migrations.DeleteModel(
            name='EventPage',
        ),
    ]
