# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170629_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.IntegerField(choices=[(1, 'Page'), (2, 'Article')], default=1),
        ),
    ]
