# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='startDate',
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('page', 'Page'), ('article', 'Article')], default='1', max_length=9),
        ),
    ]
