# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170629_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[(0, 'Page'), (1, 'Article')], default=0, max_length=9),
        ),
    ]
